---
  - debug: var=inventory_hostname
  - debug: var=ansible_hostname
  - debug: var=hostvars
  # - name: Install Boto
  #   pip: name=boto
  # - name: Install Boto3
  #   pip: name=boto3
  
  # - name: get the username running the deploy
  #   become: no
  #   local_action: command whoami
  #   register: username_on_the_host

  # - debug: var=username_on_the_host

  # - name: Register Info
  #   ec2_instance_facts:
  #     aws_access_key: '{{ec2_access_key}}'
  #     aws_secret_key: '{{ec2_secret_key}}'   
  #     region: '{{aws_region}}'
  #   register: ec2_info
  
  # - name: Print Info
  #   debug: var=ec2_info.instances[0].instance_id

  - name: Gather facts
    ec2_facts:

  - name: Conditional
    debug:
      msg: "This instance is a t1.micro : {{ ansible_ec2_instance_id }}"
    when: ansible_ec2_instance_type == "t2.micro"    