---
  - name: Set firewall default policy
    ufw: state=enabled policy=reject
  - name: Allow ssh from private network
    ufw: rule=allow port=22
  - name: Allow HTTP
    ufw: rule=allow port=80 proto=tcp
  - name: Allow HTTPS
    ufw: rule=allow port=443 proto=tcp
  - name: check ufw status
    command: ufw status
    register: myoutput
    failed_when: "'inactive' in myoutput.stdout"
    changed_when: false
    notify: restart nginx